---
kind: pipeline
type: exec
name: Msi FrontEnd Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: execute ansible
  commands:
  - ansible-playbook ansible/playbook.yml

trigger:
  branch:
  - main
  - test
  event:
  - push

node:
  machine: msi
